### ISSUE TITLE
Build agenda for January call

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bep001#15]
The next BEP001 developer call will be on **Tuesday 17 January** at 6pm CET / 5pm GMT / 12noon EDT / 9am PST. Everyone's welcome!

Please comment below if you'd like to add anything to the agenda 😸 

---

### Update

Agenda being built at https://docs.google.com/document/d/1TIsdWEi1TimAftbgf0OJnPorHif6uqclpwx4cXcx2tw/edit?usp=sharing

**Comment by Gilles86** [comment]
To be clear, the meeting has been **moved** to **Tuesday 24 January** at  6pm CET / 5pm GMT / 12noon EDT / 9am PST.

**Comment by Gilles86** [comment]
Points for discussion I can think of in an order that mmight make sense

1. The [recent discussion](https://github.com/bids-standard/bids-specification/pull/104) about governance/decision-making approaches on the main bids mailing list.
2. The general layout of the new specitfication. How do we combine the curren `bep001-naming-conventions.md`, `main.md` and `Proposal_RepetitionTime.md`. Proposal: _one_ file for the inclusion in part about RepetitionTime in original BIDS spec and _one_ file for our 'own paragraph' about multimodal sMRI data.
3. [The proposed text](https://github.com/bids-standard/bep001/pull/13) of @agahkarakuzu 
  a) `RepetitionTimePreparation` and `RepetitionTimeExcitation`
  b) Use of `suffix` instead of `modality_label`
4. Phase range limited between [0 and 2pi) (https://github.com/bids-standard/bep001/pull/17)
5. Symlinks from derivatives to sourcedata (https://github.com/bids-standard/bep001/pull/18)
6. Additional metadata fields (https://github.com/bids-standard/bep001/issues/9)
7. [Open data examples](https://github.com/bids-standard/bep001/issues/11)
8. [B1 maps and where they should go](https://github.com/bids-standard/bep001/issues/14)
9. [pybids](https://github.com/bids-standard/bep001/issues/12)
10. Timeline coming monthgs

11.  Let's make a more explicit decision/action list in our meetings!

**Comment by KirstieJane** [comment]
Awesome @Gilles86! I'm just making an agenda now! Thank you so much for thinking this through 🚀
