### ISSUE TITLE
Include `indexable_metadata` in the specification

### ISSUE THREAD

**Issue by Gilles86** [bids-standard/bep001#26]
In `bep001-naming-conventions.md` we have a 'meta'-key (belonging to a value), defined as [_indexable_metadata-<index>]. This is not ok since it hat an underscore (`_`). We should replace it with `fa`, `inv`, `echo` and `tsl`.

**Comment by chrisgorgo** [comment]
Since it is a placeholder for a list of allowed keys I would suggest replacing this with `<indexable_metadata>`

**Comment by agahkarakuzu** [comment]
Resolved [here](https://github.com/agahkarakuzu/bep001/pull/3 ).

**Comment by KirstieJane** [comment]
Action needed:

* Make explicit the fact that the 4 (current) options for the `indexable_metadata` MUST be entered in alphabetical order.
  * For example if there is more than one `indexable_metadata` field then they should appear in the file name in alphabetical order 😄 
  * Need to update the table to put `echo`, `fa`, `inv`, `tsl` in order.
* Make explict the fact that these are not free text entries, that to extend the keys for `indexable_metadata` there needs to be an update to the specification.

**Comment by KirstieJane** [comment]
Reopened as this needs to be documented in the [ProposedChangesToSpecification.md](https://github.com/bids-standard/bep001/blob/master/ProposedChangesToSpecification.md) file 😭 


I (@KirstieJane) have kinda started in #25 (bad git management rather than on purpose) see [here](https://github.com/bids-standard/bep001/pull/25/files#diff-080f3523f5a2c25654c43f53d0e8091eR12) but it isn't complete.

**Comment by Gilles86** [comment]
https://github.com/bids-standard/bep001/blob/master/ProposedChangesToSpecification.md#indexable-metadata
