### ISSUE TITLE
Merge update | fieldmap

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bep001#67]
I'm currently merging changes to the bids specification into our repository to keep us in sync with those changes.

The point of this issue is to note where there are conceptual merge conflicts (rather than just git not knowing which line information should be on!) so we can review and discuss them.

The **Fieldmap data** section needs reviewing for a way to combine the updates. Mostly gramatically as there aren't really any conceptual conflicts.

The final sentence of this section doesn't actually flow on to the four examples - recommend reading through and double checking the grammar etc.

> Data acquired to correct for B0 inhomogeneities can come in different forms. 
> B0 (static magnetic field strength pattern), B1+ (transmit field pattern),
> and B1- (receive field pattern; not yet supported) maps can be useful in
> post-processing both raw functional and anatomical data.
> 
> B0 maps are primarily used to correct for spatial distortions in functional
> data acquired with EPI sequences.
> 
> B1+ and B1- maps are mostly used in anatomical imaging, especially when
> applying quantitative MRI (qMRI) techniques.
> 
> The current version of this standard considers four different scenarios. Please 
> note that in all cases fieldmap data can be linked to a specific scan(s) it was
> acquired for by filling the IntendedFor field in the corresponding JSON file.

**Comment by ChristophePhillips** [comment]
Regarding the `fmap` folder, it was originally planned to host the B0 fieldmap, mainly for fMRI/EPI data. With advanced anatomical images, 2 other types of fieldmaps are regularly acquired: B1+ and B1 maps.
B1+ maps, aka. "B1 bias correction". These have been added in the current version of the [BEP001 proposal](https://github.com/bids-standard/bep001/blob/master/src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md#b1-fieldmaps), with the following template.
```
sub-<participant_label>/[ses-<session_label>/]
    fmap/
        sub-<participant-label>[_ses-<session_label>][_acq-<acq-label>][_run-<run_index>]_B1plusmap.nii[.gz]
        sub-<participant-label>[_ses-<session_label>][_acq-<acq-label>][_run-<run_index>]_B1plusmap.json
```
These images are thus clearly designated by the `B1plusmap` suffix.

A similar suffix, e.g. `B1minusmap`, could be introduced in order to host the B1- maps in the same `fmap` folder. The template would be pretty similar, apart for the suffix of course.
