### ISSUE TITLE
Discussion of "groupping suffixes"

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bep001#72]
Originates from https://github.com/bids-standard/bep001/issues/71 but taken into a separate issue since largely orthogonal.  I am quoting here https://github.com/bids-standard/bep001/issues/71#issuecomment-534105973 by @tiborauer :

> Modality-specific suffixes answer **why** rather than **what**

examples?

> 2\. Grouping suffix helps tools to identify images belonging to an/a compound acquisition

how often it would be necessary (i.e. `%` of the use-cases)? As I have argued in a [comment](https://github.com/bids-standard/bep001/issues/71#issuecomment-534092438) I think grouping might be less frequently used, and custom suffixes would render those files not usable by standard analysis pipelines (e.g. fmriprep).

**Comment by tiborauer** [comment]
Thank you for creating the separate thread. It is a good idea.

> examples

`bold`, `T1w`, `T2w`, `PD` images can be acquired with several sequences. `bold`, for example, can be acquired with SE or GE. Structural images are often 'mixed-weighted', which is often overlooked. That is why our BEP describes them as "images with predominant ... constrast". https://github.com/bids-standard/bep001/blob/d07489f3801a3dd39947be6d6dc9bc55200bdc7b/src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md#L175-L177 The point is these suffixes describes for what purpose these images have been acquired and how they are interpreted.

> how often it would be necessary (i.e. % of the use-cases)?

I cannot give you any valid statistics. In contrary to the structural/anatomical images already included in the BIDS specs, quantitative mapping introduced by this BEP (e.g. MPM, MP2RAGE, MTR, MTS) requires post-processing. It means, & of the use-cases is very high among people interested in this BEP, but may be low among those people interested in only e.g. fMRI.

**Comment by Gilles86** [comment]
my 2 cents:

Actually, I see it exactly the other way around: the _current_ anatomical suffices of BIDS describe _why_ rather than _what_. There is no such things as "a T1-weighted image". What the suffix 'T1w' currently communicates is, in my view, something like "Look fella, this is an image where Gray Matter is hypo- and white matter is hyper-intense. CSF is mostly black. FSL and fmriprep can deal with this...". The latter being the why.

This is different from a MP2RAGE and/or T1-map with very precisely defined MR parameters. There you really describe _what_ the image contains from a physics point-of-view.
